### ISSUE TITLE
Problem running rootcling:  error with -fno-plt flag

### ISSUE THREAD

**Issue by whart222** [conda-forge/cppyy-backend-feedstock#23]
- [ X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I'm running into an issue using cppyy with conda on Ubuntu.  The cppyy setup fails when running *rootcling*, when it fails due to an unexpected compiler flag '-fno-plt'.  The problem appears to be that the conda environment is built with GCC using this flag, and somehow it is being passed into rootcling.  (See the ticket submitted to cppyy: https://bitbucket.org/wlav/cppyy/issues/298/problem-using-cppyy-via-conda).

The latest commits to cppyy-backend appear to include a work-around for this issue (see https://bitbucket.org/wlav/cppyy-backend/src/master/cling/src/etc/dictpch/).  However, I cannot tell if the latest conda distribution of cppyy-backend includes this fix.  If so, then there appears to be a persistent bug.  Perhaps *rootcling* needs to be rebuilt?  My conda clang installation appears to accept this compiler option.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

cppyy 1.9.2 py38hc973b2a_0 conda-forge
cppyy-backend 1.14.1 py38hbf85e49_0 conda-forge
cppyy-cling 6.21.4 py38h7941ff8_1 conda-forge
cpycppyy 1.12.1 py38h1fd1430_0 conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
    active environment : pperf
    active env location : /home/wehart/anaconda3/envs/pperf
            shell level : 2
       user config file : /home/wehart/.condarc
 populated config files : /home/wehart/.condarc
          conda version : 4.8.0
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __glibc=2.27
       base environment : /home/wehart/anaconda3  (writable)
           channel URLs : http://conda.anaconda.org/gurobi/linux-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/wehart/anaconda3/pkgs
                          /home/wehart/.conda/pkgs
       envs directories : /home/wehart/anaconda3/envs
                          /home/wehart/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.0 requests/2.21.0 CPython/3.7.3 Linux/5.4.0-59-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by saraedum** [comment]
Sorry for the late reply. This seems to be fixed in 1.9.3 which was just released.

**Comment by saraedum** [comment]
So, more concretely, it should be ready once this has been merged: https://github.com/conda-forge/cppyy-feedstock/pull/41

**Comment by saraedum** [comment]
I'll close this since it should be fixed by now. Feel free to reopen if it is not fixed.
